FROM ubuntu:20.04
RUN  apt-get update \
  && apt-get install -y wget curl python3 python3-pip \
  && rm -rf /var/lib/apt/lists/*

RUN wget https://raw.githubusercontent.com/aheckmann/m/master/bin/m && chmod +x ./m
RUN ./m install <%= mongo_version %>
